### ISSUE TITLE
Number appearing before the negative signal

### ISSUE THREAD

**Issue by DavidFerrs** [joutvhu/number_text_input_formatter#11]
When i type the decimal separator caracter after the negative signal caracter, a 0 appears before the negative signal
 

-  input text: "-."

- output text: "0-.00"

 

<img width="477" alt="Captura de Tela 2024-01-22 às 17 05 11" src="https://github.com/joutvhu/number_text_input_formatter/assets/81036027/19259b9e-2f56-41eb-9409-963d9200b616">

<br><br>

```
    inputFormatterEnUs = NumberTextInputFormatter(
      integerDigits: 12,
      decimalDigits: widget.disableDecimal ? 0 : 2,
      maxValue: '999999999999.99', // hundred billion
      decimalSeparator: '.',
      groupDigits: 3,
      groupSeparator: ',',
      allowNegative: true,
      overrideDecimalPoint: false,
      insertDecimalPoint: false,
      insertDecimalDigits: false,
    );
```

version on yaml file: _number_text_input_formatter: ^1.0.0+7_

The code is running in flutterWeb

**Comment by joutvhu** [comment]
Fixed in version `1.0.0+8`
