### ISSUE TITLE
Removed the default decimal when input . or ,

### ISSUE THREAD

**Issue by vickygaugau** [joutvhu/number_text_input_formatter#3]
[](url)There is my input formatter
NumberTextInputFormatter(
                            integerDigits: 20,
                            decimalSeparator: '.',
                            groupDigits: 3,
                            groupSeparator: ',',
                            allowNegative: false,
                            overrideDecimalPoint: false,
                            insertDecimalPoint: false,
                            insertDecimalDigits: false,
                          ),
with decimalDigits = null
when i input the dot(.) or the comma (,)
It is included default '.0'
How can i removed the default, just input number what i input
Thanks

https://user-images.githubusercontent.com/4328044/233548224-cb4947eb-2f06-471b-883f-b43f04e193ff.mov

**Comment by joutvhu** [comment]
@vickygaugau  Use version v1.0.0+4 and set `fixNumber: false`
