### ISSUE TITLE
Thousands operator wrongly shown for negative value

### ISSUE THREAD

**Issue by rivella50** [joutvhu/number_text_input_formatter#5]
If the current value is negative and has digits mod 3 == 0 the thousands symbol is shown:
![Screenshot 2023-04-28 at 13 05 34](https://user-images.githubusercontent.com/54292/235132021-55f73775-aa7a-4a7c-ad84-c1664f8c46bc.png)

Also: How can an initialValue be defined and automatically be formatted correctly?

This is my source code:
```
TextFormField(
  initialValue: 
      2045.55.toStringAsFixed(2),                
  style: const TextStyle(
        fontSize: 30,
      ),
  inputFormatters: [
    CurrencyTextInputFormatter(
      allowNegative: true,
      prefix: '€ ', 
    )
  ],
  keyboardType: TextInputType.number,
  //onChanged: (value) => print(value),
)
```

**Comment by joutvhu** [comment]
Fixed in version 1.0.0+6

**Comment by rivella50** [comment]
Thank you. Do you also have an answer to my question regarding formatting an `initialValue`?

**Comment by joutvhu** [comment]
The formatter will not be called when you set `initialValue`.
You can manually format the value before assigning into `initialValue`.

```dart
var formatter = CurrencyTextInputFormatter(
  allowNegative: true,
  prefix: '€ ',
);

TextFormField(
  initialValue: formatter
      .formatEditUpdate(TextEditingValue.empty, TextEditingValue(text: 2045.55.toStringAsFixed(2)))
      .text,
  style: const TextStyle(
    fontSize: 30,
  ),
  inputFormatters: [
    formatter
  ],
  keyboardType: TextInputType.number,
)
```
